---
title: Publications
---

Below is a curated list of peer-reviewed publications related to
**AI for geohazard forecasting, modelling, and response**.

## Journal Articles

1. **Nava, L.**, Mondini, A., Bhuyan, K., Fang, C., Monserrat, O., Novellino, A., & Catani, F. (2026).  
   *Sentinel-1 SAR-based globally distributed landslide detection by deep neural networks.*  
   **Geoscientific Model Development**, 19(1), 167–185. [DOI](https://doi.org/10.5194/gmd-19-167-2026)

2. **Dong, Y.**, **Nava, L.**, & Catani, F. (2025).  
   *Improving ground deformation classification by integrating InSAR time series with geospatial information.*  
   **IEEE Transactions on Geoscience and Remote Sensing**, 63, 1–12. [DOI](https://doi.org/10.1109/TGRS.2025.3635271)

3. **Nava, L.**, Kuglitsch, M. M., Selby, J., Bray, A., Kennedy, P., Lontsi, J., et al. (2025).  
   *Introducing AI practitioners to international standards through online competitions.*  
   **npj Natural Hazards**, 2(1), 102. [DOI](https://doi.org/10.1038/s44304-025-00154-8)

4. Tang, X., Lu, Z., Fan, X., Yan, X., Yuan, X., Li, D., … **Nava, L.**, & Catani, F. (2025).  
   *Mamba for landslide detection: a lightweight model for mapping landslides with very high-resolution images.*  
   **IEEE Transactions on Geoscience and Remote Sensing**, 63, 1–17. [DOI](https://doi.org/10.1109/TGRS.2025.3598446)

5. **Nava, L.**, Novellino, A., Fang, C., Bhuyan, K., Leeming, K., Alvarez, I. G., et al. (2025).  
   *AI-driven rapid landslide mapping following the 2024 Hualien City earthquake in Taiwan.*  
   **Natural Hazards and Earth System Sciences**, 25(7), 2371–2377. [DOI](https://doi.org/10.5194/nhess-2024-146)

6. Dramsch, J., Kuglitsch, M. M., Fernández-Torres, M.-Á., Toreti, A., Albayrak, R. A., **Nava, L.**, et al. (2025).  
   *Explainability can foster trust in artificial intelligence in geoscience.*  
   **Nature Geoscience**, 1–3. [DOI](https://doi.org/10.1038/s41561-025-01639-x)

7. Bhuyan, K., Rana, K., Ozturk, U., **Nava, L.**, Rosi, A., Meena, S. R., et al. (2025).  
   *Towards automatic delineation of landslide source and runout.*  
   **Engineering Geology**, 345, 107866. [DOI](https://doi.org/10.1016/j.enggeo.2024.107866)

8. Fang, C., Fan, X., Wang, X., **Nava, L.**, Zhong, H., Dong, X., et al. (2024).  
   *A globally distributed dataset of coseismic landslide mapping via multi-source high-resolution remote sensing images.*  
   **Earth System Science Data**, 16, 4817–4858. [DOI](https://doi.org/10.5194/essd-16-4817-2024)

9. **Nava, L.**, Tordesillas, A., Qian, G., & Catani, F. (2024).  
   *Displacement residuals reveal landslide regime shifts.*  
   **Landslides**, 1–16. [DOI](https://doi.org/10.1007/s10346-024-02353-2)

10. **Nava, L.***, Carraro, E., Reyes-Carmona, C., Puliero, S., Bhuyan, K., Rosi, A., et al. (2023).  
    *Landslide displacement forecasting using deep learning and monitoring data across selected sites.*  
    **Landslides**, 1–19. [DOI](https://doi.org/10.1007/s10346-023-02104-9)

11. **Nava, L.**, Bhuyan, K., Meena, S. R., Monserrat, O., & Catani, F. (2022).  
    *Rapid mapping of landslides on SAR data by attention U-Net.*  
    **Remote Sensing**, 14(6), 1449. [DOI](https://doi.org/10.3390/rs14061449)

12. **Nava, L.**, Cuevas, M., Meena, S. R., Catani, F., & Monserrat, O. (2022).  
    *Artisanal and small-scale mine detection in semi-desertic areas by improved U-Net.*  
    **IEEE Geoscience and Remote Sensing Letters**, 19, 1–5. [DOI](https://doi.org/10.1109/LGRS.2022.3220487)

13. **Nava, L.**, Monserrat, O., & Catani, F. (2022).  
    *Improving landslide detection on SAR data through deep learning.*  
    **IEEE Geoscience and Remote Sensing Letters**, 19, 1-5. [DOI](https://doi.org/10.1109/LGRS.2021.3127073)

## Book Chapters

- Catani, F., **Nava, L.**, & Bhuyan, K. (2025).  
  *Artificial intelligence applications for landslide mapping and monitoring on EO data.*  
  In **Earth Observation Applications to Landslide Mapping, Monitoring and Modeling** (pp. 119–145). Elsevier.  [DOI](https://doi.org/10.1016/B978-0-12-823868-4.00007-6)
